### ISSUE TITLE
Monitor on- and off events for Ambisense valves

### ISSUE THREAD

**Issue by jiridj** [thomasgermain/pymultiMATIC#34]
Hi Thomas,

While looking for API documentation on my Vaillant setup I came across this wonderful project. I have been looking in more detail into it, but I can't seem to find what I'm looking for. I'll just ask to be sure. ;-)

I have multiple AmbiSense Valves connected to the the internet module. Each valve controls the temperature in a particular room. The standard app allows you to set temperatures, but not much more.

I'm interested in collecting information on when a particular valve opens and closes. In other words, when is which room being heated. Is that information available anywhere in the APIs you have found? 

Thanks!

jiri

**Comment by thomasgermain** [comment]
Hi Jiri,

thanks for your input :)

I also have multiple ambisense valves and one heating floor and I already had a deep look into that problem. In summary: no, this information is not directly available, but...

 Taking my configuration as example:
- heating floor = Zone 2 in the VRC 700
- group of ambisense valves (= Room) = Zone 1 in the VRC 700 

For a `Zone` you have an `active_function` attribute. From what I can see this is switching between `standby` and `heating` (I think it can also be `cooling` but I don't have any cooling system related to vaillant). So you can know what the zone is doing. So for a zone we can get it directly through the API.

Here comes the tricky part: now speaking about `Room`, from the VRC 700 point of view, rooms don't exist (it only knows Zone 1 and Zone 2). During my tests I was able to see the following:
- `Room 1`, let's say actual temperature: 20, target temperature: 25
- The system will somehow send false information to the VRC 700: it will set the `Zone 1` actual temp to 20 and the target temp to 25. So this system thinks it will heat a zone (because it is not aware of room). And because we are inside a zone context, the `active_function` attribute is available, so you may know the zone is heating and you can conclude the room is heating.
Now, if you have multiple rooms, you don't know exactly which one is heating, maybe you can check actual temperature and target temperature, but i'm pretty sure a room won't heat if the actual temperature is 0.5 below the target temperature.

Hope it can help you.

Thomas

**Comment by jiridj** [comment]
Ah, that is interesting! Digging deeper into your documentation I noticed that rooms also have the actual temperature in their data structure, not just zones.

A boolean on the device (valve open or closed) would have been nice, but comparing actual to target temperature should indeed to the trick.

I won't get to this right away, but when I do I will provide feedback. 

Thanks!

**Comment by thomasgermain** [comment]
You are welcome :smiley: 

The goal of the project here is the reflect what is available from the API, so I try to limit as most as possible to "guess" or interpret some data. I prefer to have the end user  (you :stuck_out_tongue: ) doing it based on his needs. 

I could add the boolean, but i'm not 100% sure when the valve is open or close: as I said, if there is 0.5 degree difference between actual and target temperature, in some case the system may heat or not (maybe because of outdoor temperature, or maybe the boiler is already heating something else so it costs nothing to just send a few hot water in that room, etc.)
